{% set name = "litespi" %}
{% set version = "2025.08" %}
{% set sha256 = "a718296b748e10b78cd85f4d83b242c50cd2cae4be3c8a4398efd3b3a99e6971" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/litex-hub/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litespi_gen = litespi.gen:main

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - litex ~={{ version }}*
    - liteiclink ~={{ version }}*
    - migen
    - packaging
    - pyyaml

test:
  requires:
    - python {{ python_min }}
  imports:
    - litespi
  commands:
    - litespi_gen --help

about:
  home: https://github.com/litex-hub/litespi
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable SPI core
  description: Small footprint and configurable SPI core
  dev_url: https://github.com/litex-hub/litespi

extra:
  recipe-maintainers:
    - timkpaine
