{% set name = "litespi" %}
{% set version = "2024.08" %}
{% set sha256 = "03e386809bc9ca1ca11f64a5a88efcae62b2e00dff0ff8ed21d12cacd536e990" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/litex-hub/{{ name }}/archive/refs/tags/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-build-isolation --no-deps
  entry_points:
    - litespi_gen = litespi.gen:main

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - litex ={{ version }}
    - liteiclink ={{ version }}
    - migen
    - packaging
    - pyyaml

test:
  imports:
    - litespi
  commands:
    - litespi_gen --help

about:
  home: https://github.com/litex-hub/litespi
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Small footprint and configurable SPI core
  description: Small footprint and configurable SPI core
  dev_url: https://github.com/litex-hub/litespi

extra:
  recipe-maintainers:
    - timkpaine
